Давайте найдем заведения `Taco Bell` или заведения, которые находятся в городе Нью-Йорк. При этом обязательно, чтобы в названии меню **не было** `Volcano Taco` и `Fresco Soft Taco` (именно таких значений колонки). Данные нужно сохранить в датафрейм `result`.

In [18]:
import pandas as pd

data = pd.read_csv('data.csv')
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77260 entries, 0 to 77259
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 77260 non-null  object
 1   address            77260 non-null  object
 2   categories         77260 non-null  object
 3   city               77260 non-null  object
 4   cuisines           38384 non-null  object
 5   dateAdded          77260 non-null  object
 6   dateUpdated        77260 non-null  object
 7   latitude           55636 non-null  float64
 8   longitude          55636 non-null  float64
 9   menus.category     3729 non-null   object
 10  menus.currency     40511 non-null  object
 11  menus.dateSeen     77260 non-null  object
 12  menus.description  29323 non-null  object
 13  menus.name         77260 non-null  object
 14  name               77257 non-null  object
 15  province           77257 non-null  object
dtypes: float64(2), object(14)
memory usage: 9.4+ MB

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
0,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,Restaurant Delivery Service,2016-03-02T11:49:34Z,2017-02-01T18:04:44Z,39.561570,-95.121020,NaN,NaN,2017-02-01T18:04:44Z,NaN,Taco,Gambino's Pizza,KS
1,AVwc__cikufWRAb51QjV,610 Commercial St,"Restaurant Delivery Service,Restaurants,Pizza,...",Atchison,Restaurant Delivery Service,2016-03-02T11:49:34Z,2017-02-01T18:04:44Z,39.561570,-95.121020,NaN,NaN,2016-03-02T11:49:34Z,"Beef, onion, cheddar cheese, lettuce, refried...",Taco,Gambino's Pizza,KS
2,AVwc__dF_7pvs4fz1Ncy,9521 Morton Davis Dr,"Golf Course, American Restaurant, and Resort",Patterson,NaN,2016-10-14T01:58:25Z,2016-10-14T01:58:25Z,37.401855,-121.266703,NaN,NaN,2016-10-14T01:58:25Z,"Beef barbacoa or chicken, spanish rice, pico d...",Smotherd Burrito,Diablo Grande Golf & Country Club,Grayson
3,AVwc__kCByjofQCxkdm-,10550 W I 25 Frontage Rd,Fast Food Restaurant,Longmont,NaN,2016-09-09T17:30:34Z,2016-10-04T05:15:17Z,NaN,NaN,NaN,NaN,2016-09-09T17:30:34Z,NaN,Sausage Burrito,Mcdonald's,Niwot
4,AVwc__WtByjofQCxkdkR,8495 W 3rd St,"Mexican Restaurant Mid-City West,Mexican Resta...",Los Angeles,Mexican,2016-05-19T11:50:25Z,2016-09-11T00:06:37Z,34.080724,-118.389578,NaN,NaN,2016-05-19T11:50:25Z,"Wahoo, avocado, cabbage, pico de gallo and av...",Wahoo Tacogrilled,Baja Fresh Mexican Grill,Bicentennial

In [30]:
result = data[
    ((data['name'] == 'Taco Bell') | (data['city'] == 'New York'))
    & (~(data['menus.name'].isin(['Volcano Taco', 'Fresco Soft Taco'])))
]
result

,id,address,categories,city,cuisines,dateAdded,dateUpdated,latitude,longitude,menus.category,menus.currency,menus.dateSeen,menus.description,menus.name,name,province
131,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Volcano Burrito,Taco Bell,NH
132,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Taco 12 Pack,Taco Bell,NH
133,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Grilled Steak Soft Taco,Taco Bell,NH
135,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Fresco Grilled Steak Soft Taco,Taco Bell,NH
136,AVwc_9yCByjofQCxkdRX,322 S. Broadway,"Fast Food,Restaurants,Mexican,Breakfast,Vegeta...",Salem,Mexican,2016-03-28T06:01:51Z,2017-06-27T10:01:48Z,42.755023,-71.209440,NaN,NaN,"2016-03-28T06:01:51Z,2016-06-06T16:15:44Z",NaN,Fresco Crunchy Taco,Taco Bell,NH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76904,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Tacos,USD,2016-08-21T00:00:00Z,NaN,Trio of Tacos,Hell's Kitchen,Nyc
76905,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,"Huevos, Etc.",USD,2016-08-07T00:00:00Z,NaN,Brunch Burrito,Hell's Kitchen,Nyc
76906,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Botanas,USD,2016-08-07T00:00:00Z,NaN,Grilled Chicken Mini Burrito,Hell's Kitchen,Nyc
76907,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Botanas,USD,2016-08-07T00:00:00Z,with pumpkin seed guacamole,Grilled Vegetable Mini Burrito,Hell's Kitchen,Nyc
76908,AVweZN9nByjofQCxxz4o,754 Ninth Ave,Restaurant,New York,"Mexican, American, Traditional Mexican",2015-10-19T20:44:15Z,2016-08-22T11:24:07Z,40.763858,-73.988327,Main,NaN,2016-08-21T00:00:00Z,NaN,Burritos,Hell's Kitchen,Nyc